export const cardTypeSeeds = [
  {
    id: 1,
    typeName: '王者点券直充',
    unsoldCount: 126,
    soldCount: 84,
    totalStock: 210,
    deliveryChannel: '自动发卡',
    inventoryCost: 13240,
    averagePrice: 68.8,
    cardPrefix: 'WZ-',
    passwordPrefix: 'K-',
    separatorText: '----',
    templateCount: 2,
    isDeleted: 0,
    createdOffsetDays: -42,
    createdHour: 10,
    createdMinute: 30,
    updatedOffsetDays: -1,
    updatedHour: 9,
    updatedMinute: 20,
    deletedOffsetDays: null,
    deletedHour: null,
    deletedMinute: null,
    deletedBy: null,
  },
  {
    id: 2,
    typeName: '视频会员周卡',
    unsoldCount: 302,
    soldCount: 418,
    totalStock: 720,
    deliveryChannel: '自动发卡',
    inventoryCost: 5068,
    averagePrice: 19.9,
    cardPrefix: 'VIP-',
    passwordPrefix: 'PW-',
    separatorText: '|',
    templateCount: 1,
    isDeleted: 0,
    createdOffsetDays: -35,
    createdHour: 11,
    createdMinute: 0,
    updatedOffsetDays: -1,
    updatedHour: 17,
    updatedMinute: 35,
    deletedOffsetDays: null,
    deletedHour: null,
    deletedMinute: null,
    deletedBy: null,
  },
  {
    id: 3,
    typeName: '音乐会员月卡',
    unsoldCount: 88,
    soldCount: 163,
    totalStock: 251,
    deliveryChannel: '模板变量',
    inventoryCost: 2890,
    averagePrice: 14.5,
    cardPrefix: 'YY-',
    passwordPrefix: 'MK-',
    separatorText: '/',
    templateCount: 2,
    isDeleted: 0,
    createdOffsetDays: -28,
    createdHour: 14,
    createdMinute: 0,
    updatedOffsetDays: -2,
    updatedHour: 18,
    updatedMinute: 10,
    deletedOffsetDays: null,
    deletedHour: null,
    deletedMinute: null,
    deletedBy: null,
  },
  {
    id: 4,
    typeName: 'Switch 在线季卡',
    unsoldCount: 34,
    soldCount: 49,
    totalStock: 83,
    deliveryChannel: '自动发卡',
    inventoryCost: 3210,
    averagePrice: 92,
    cardPrefix: 'SW-',
    passwordPrefix: 'ON-',
    separatorText: '#',
    templateCount: 1,
    isDeleted: 0,
    createdOffsetDays: -22,
    createdHour: 16,
    createdMinute: 40,
    updatedOffsetDays: -3,
    updatedHour: 20,
    updatedMinute: 15,
    deletedOffsetDays: null,
    deletedHour: null,
    deletedMinute: null,
    deletedBy: null,
  },
  {
    id: 5,
    typeName: '海外加速器季卡',
    unsoldCount: 41,
    soldCount: 27,
    totalStock: 68,
    deliveryChannel: '自动发卡',
    inventoryCost: 1980,
    averagePrice: 39.9,
    cardPrefix: 'VPN-',
    passwordPrefix: 'G-',
    separatorText: '-',
    templateCount: 1,
    isDeleted: 1,
    createdOffsetDays: -18,
    createdHour: 12,
    createdMinute: 0,
    updatedOffsetDays: -2,
    updatedHour: 8,
    updatedMinute: 30,
    deletedOffsetDays: -2,
    deletedHour: 8,
    deletedMinute: 30,
    deletedBy: '系统管理员',
  },
  {
    id: 6,
    typeName: '观影会员联合卡',
    unsoldCount: 22,
    soldCount: 39,
    totalStock: 61,
    deliveryChannel: '模板变量',
    inventoryCost: 1588,
    averagePrice: 33.9,
    cardPrefix: 'MOV-',
    passwordPrefix: 'UN-',
    separatorText: '+',
    templateCount: 3,
    isDeleted: 1,
    createdOffsetDays: -15,
    createdHour: 19,
    createdMinute: 10,
    updatedOffsetDays: -5,
    updatedHour: 23,
    updatedMinute: 0,
    deletedOffsetDays: -5,
    deletedHour: 23,
    deletedMinute: 0,
    deletedBy: '运营分析师',
  },
] as const;

export const cardDeliverySeeds = [
  {
    id: 1,
    cardTypeId: 1,
    productTitle: '王者荣耀 648 点券直充',
    salePrice: 68.8,
    category: '游戏充值',
    storeName: '潮玩优选店',
    contentMode: '卡密直发',
    deliveryPolicy: '买家付款后发货',
    enabled: 1,
    status: '销售中',
    updatedOffsetDays: -1,
    updatedHour: 11,
    updatedMinute: 20,
  },
  {
    id: 2,
    cardTypeId: 2,
    productTitle: '爱奇艺会员周卡',
    salePrice: 19.9,
    category: '影音会员',
    storeName: '美妆折扣馆',
    contentMode: '模板变量',
    deliveryPolicy: '买家收货后赠送',
    enabled: 1,
    status: '销售中',
    updatedOffsetDays: -1,
    updatedHour: 15,
    updatedMinute: 0,
  },
  {
    id: 3,
    cardTypeId: 3,
    productTitle: '网易云黑胶月卡',
    salePrice: 14.5,
    category: '音乐会员',
    storeName: '3C数码仓',
    contentMode: '卡密直发',
    deliveryPolicy: '好评后赠送',
    enabled: 0,
    status: '手动下架',
    updatedOffsetDays: -3,
    updatedHour: 10,
    updatedMinute: 40,
  },
  {
    id: 4,
    cardTypeId: 4,
    productTitle: 'Switch 在线会员季卡',
    salePrice: 92,
    category: '游戏会员',
    storeName: '潮玩优选店',
    contentMode: '卡密直发',
    deliveryPolicy: '买家付款后发货',
    enabled: 1,
    status: '待发布',
    updatedOffsetDays: -2,
    updatedHour: 9,
    updatedMinute: 10,
  },
] as const;

export const cardComboSeeds = [
  {
    id: 1,
    comboName: '影音会员双拼',
    comboContent: '视频会员周卡 + 音乐会员月卡',
    comboType: '固定组合',
    status: '销售中',
    createdOffsetDays: -20,
    createdHour: 12,
    createdMinute: 0,
    updatedOffsetDays: -1,
    updatedHour: 16,
    updatedMinute: 30,
  },
  {
    id: 2,
    comboName: '游戏权益礼包',
    comboContent: '王者点券直充 + Switch 在线季卡',
    comboType: '阶梯组合',
    status: '销售中',
    createdOffsetDays: -16,
    createdHour: 9,
    createdMinute: 30,
    updatedOffsetDays: -2,
    updatedHour: 19,
    updatedMinute: 15,
  },
  {
    id: 3,
    comboName: '新客尝鲜包',
    comboContent: '视频会员周卡 + 海外加速器季卡',
    comboType: '活动组合',
    status: '手动下架',
    createdOffsetDays: -12,
    createdHour: 14,
    createdMinute: 10,
    updatedOffsetDays: -4,
    updatedHour: 13,
    updatedMinute: 45,
  },
] as const;

export const cardTemplateSeeds = [
  {
    id: 1,
    templateName: '邀请再次购买',
    templateContent: '感谢支持，本次卡密已为你准备完成，欢迎再次购买。',
    templateStatus: '启用',
    randomEnabled: 1,
    createdOffsetDays: -30,
    createdHour: 10,
    createdMinute: 0,
    updatedOffsetDays: -1,
    updatedHour: 19,
    updatedMinute: 0,
  },
  {
    id: 2,
    templateName: '自动发货通知',
    templateContent: '付款成功后会自动发卡，如有异常请联系在线客服处理。',
    templateStatus: '启用',
    randomEnabled: 1,
    createdOffsetDays: -25,
    createdHour: 9,
    createdMinute: 20,
    updatedOffsetDays: -2,
    updatedHour: 20,
    updatedMinute: 10,
  },
  {
    id: 3,
    templateName: '售后补发说明',
    templateContent: '如卡密失效，请附订单截图，我们会优先补发处理。',
    templateStatus: '停用',
    randomEnabled: 0,
    createdOffsetDays: -18,
    createdHour: 15,
    createdMinute: 0,
    updatedOffsetDays: -6,
    updatedHour: 11,
    updatedMinute: 45,
  },
] as const;

export const cardRecordSeeds = [
  {
    id: 1,
    recordType: '发卡记录',
    orderNo: 'GF2026030900821',
    orderStatus: '已付款',
    storeName: '潮玩优选店',
    buyerName: '小布2345',
    cardType: '王者点券直充',
    sendStatus: '已发卡',
    linkUrl: 'https://example.com/card/821',
    paidOffsetDays: 0,
    paidHour: 9,
    paidMinute: 12,
    confirmedOffsetDays: null,
    confirmedHour: null,
    confirmedMinute: null,
    ratedOffsetDays: null,
    ratedHour: null,
    ratedMinute: null,
    sentOffsetDays: 0,
    sentHour: 9,
    sentMinute: 13,
  },
  {
    id: 2,
    recordType: '卡密记录',
    orderNo: 'GF2026030800674',
    orderStatus: '已发货',
    storeName: '3C数码仓',
    buyerName: '安宁18',
    cardType: '音乐会员月卡',
    sendStatus: '补发完成',
    linkUrl: 'https://example.com/card/674',
    paidOffsetDays: -1,
    paidHour: 14,
    paidMinute: 28,
    confirmedOffsetDays: -1,
    confirmedHour: 20,
    confirmedMinute: 35,
    ratedOffsetDays: null,
    ratedHour: null,
    ratedMinute: null,
    sentOffsetDays: -1,
    sentHour: 14,
    sentMinute: 31,
  },
  {
    id: 3,
    recordType: '货源记录',
    orderNo: 'GF2026030600551',
    orderStatus: '已完成',
    storeName: '美妆折扣馆',
    buyerName: '景语63',
    cardType: '视频会员周卡',
    sendStatus: '已入库',
    linkUrl: 'https://example.com/card/551',
    paidOffsetDays: -3,
    paidHour: 11,
    paidMinute: 5,
    confirmedOffsetDays: -2,
    confirmedHour: 18,
    confirmedMinute: 10,
    ratedOffsetDays: -1,
    ratedHour: 9,
    ratedMinute: 0,
    sentOffsetDays: -3,
    sentHour: 11,
    sentMinute: 6,
  },
  {
    id: 4,
    recordType: '发卡记录',
    orderNo: 'GF2026030500488',
    orderStatus: '售后中',
    storeName: '潮玩优选店',
    buyerName: '时安90',
    cardType: 'Switch 在线季卡',
    sendStatus: '等待补发',
    linkUrl: 'https://example.com/card/488',
    paidOffsetDays: -4,
    paidHour: 16,
    paidMinute: 12,
    confirmedOffsetDays: -3,
    confirmedHour: 10,
    confirmedMinute: 10,
    ratedOffsetDays: null,
    ratedHour: null,
    ratedMinute: null,
    sentOffsetDays: -4,
    sentHour: 16,
    sentMinute: 15,
  },
] as const;

export const fundAccountSeed = {
  id: 1,
  accountName: '闲管家主账户',
  availableBalance: 5820.56,
  pendingWithdrawal: 368,
  frozenBalance: 120,
  depositBalance: 3000,
  totalRecharged: 12880,
  totalPaidOut: 5412.3,
  status: '正常',
  updatedOffsetDays: 0,
  updatedHour: 11,
  updatedMinute: 5,
} as const;

export const fundBillSeeds = [
  {
    tradeOffsetDays: -8,
    tradeHour: 12,
    tradeMinute: 0,
    storeId: 1,
    billNo: 'BILL202603010001',
    merchantOrderNo: 'ORDER-SUB-20260301',
    paymentNo: 'PAY202603010001',
    itemName: '会员年费订购',
    itemInfo: '高级版会员一年',
    amount: -138,
    tradeType: '支出',
    tradeMethod: '支付宝',
    balanceAfter: 5248.5,
    remark: '会员服务自动扣款',
  },
  {
    tradeOffsetDays: -6,
    tradeHour: 16,
    tradeMinute: 32,
    storeId: 2,
    billNo: 'BILL202603030012',
    merchantOrderNo: 'RECHARGE-20260303',
    paymentNo: 'PAY202603030012',
    itemName: '账户充值',
    itemInfo: '运营手动充值',
    amount: 1000,
    tradeType: '入账',
    tradeMethod: '支付宝',
    balanceAfter: 6248.5,
    remark: '补充推广预算',
  },
  {
    tradeOffsetDays: -5,
    tradeHour: 9,
    tradeMinute: 18,
    storeId: 1,
    billNo: 'BILL202603040021',
    merchantOrderNo: 'DEPOSIT-20260304',
    paymentNo: 'PAY202603040021',
    itemName: '保证金缴纳',
    itemInfo: '供货商服务保证金',
    amount: -3000,
    tradeType: '冻结',
    tradeMethod: '余额',
    balanceAfter: 3248.5,
    remark: '保证金冻结至专用账户',
  },
  {
    tradeOffsetDays: -2,
    tradeHour: 19,
    tradeMinute: 30,
    storeId: 3,
    billNo: 'BILL202603070007',
    merchantOrderNo: 'ORDER-WX-20260307',
    paymentNo: 'PAY202603070007',
    itemName: '微信通知年费',
    itemInfo: '公众号消息提醒服务',
    amount: -88,
    tradeType: '支出',
    tradeMethod: '余额',
    balanceAfter: 5910.56,
    remark: '服务续费',
  },
] as const;

export const fundWithdrawalSeeds = [
  {
    id: 1,
    withdrawalNo: 'TX202603090001',
    tradeOffsetDays: 0,
    tradeHour: 10,
    tradeMinute: 15,
    storeId: 1,
    tradeNo: 'CAP202603090001',
    tradeType: '余额提现',
    amount: 368,
    fee: 8,
    arrivalAmount: 360,
    availableBalance: 5820.56,
    status: 'pending',
    method: '支付宝',
    receivingAccount: 'xiaobu@alipay',
    reviewRemark: '待财务复核',
  },
  {
    id: 2,
    withdrawalNo: 'TX202603040003',
    tradeOffsetDays: -5,
    tradeHour: 11,
    tradeMinute: 42,
    storeId: 2,
    tradeNo: 'CAP202603040003',
    tradeType: '佣金提现',
    amount: 520,
    fee: 10,
    arrivalAmount: 510,
    availableBalance: 5618.22,
    status: 'paid',
    method: '银行卡',
    receivingAccount: '招商银行尾号 6621',
    reviewRemark: '已打款',
  },
  {
    id: 3,
    withdrawalNo: 'TX202603020002',
    tradeOffsetDays: -7,
    tradeHour: 15,
    tradeMinute: 5,
    storeId: 3,
    tradeNo: 'CAP202603020002',
    tradeType: '余额提现',
    amount: 260,
    fee: 0,
    arrivalAmount: 260,
    availableBalance: 5980.56,
    status: 'rejected',
    method: '支付宝',
    receivingAccount: 'old-account@alipay',
    reviewRemark: '收款账号信息不完整',
  },
] as const;

export const fundDepositSeeds = [
  {
    id: 1,
    storeId: 1,
    depositType: '供货商保证金',
    industry: '数字商品',
    status: '已缴纳',
    amount: 3000,
    operateOffsetDays: -20,
    operateHour: 18,
    operateMinute: 0,
    actionLabel: '去查看',
    tradeOffsetDays: -20,
    tradeHour: 18,
    tradeMinute: 0,
    paymentNo: 'DEP202602180001',
    tradeAmount: 3000,
    tradeType: '缴纳',
    description: '用于供货服务履约保障',
  },
  {
    id: 2,
    storeId: 2,
    depositType: '代理商保证金',
    industry: '服务代理',
    status: '退保审核中',
    amount: 800,
    operateOffsetDays: -3,
    operateHour: 10,
    operateMinute: 25,
    actionLabel: '查看进度',
    tradeOffsetDays: -3,
    tradeHour: 10,
    tradeMinute: 25,
    paymentNo: 'DEP202603060002',
    tradeAmount: 800,
    tradeType: '退保',
    description: '代理商退出流程处理中',
  },
] as const;

export const fundOrderSeeds = [
  {
    id: 1,
    storeId: 1,
    createdOffsetDays: -7,
    createdHour: 20,
    createdMinute: 28,
    paidOffsetDays: -7,
    paidHour: 20,
    paidMinute: 29,
    orderItem: '高级版会员',
    cycleText: '1 年',
    orderContent: '高级版会员续费',
    paidAmount: 138,
    merchantOrderNo: 'ORDER-SUB-20260302',
    billNo: 'BILL202603020131',
    paymentNo: 'PAY202603020131',
  },
  {
    id: 2,
    storeId: 3,
    createdOffsetDays: -2,
    createdHour: 9,
    createdMinute: 12,
    paidOffsetDays: -2,
    paidHour: 9,
    paidMinute: 13,
    orderItem: '微信通知服务',
    cycleText: '1 年',
    orderContent: '公众号消息提醒服务',
    paidAmount: 88,
    merchantOrderNo: 'ORDER-WX-20260307',
    billNo: 'BILL202603070007',
    paymentNo: 'PAY202603070007',
  },
] as const;

export const fundAgentSeeds = [
  {
    id: 1,
    memberName: '小布2345',
    versionName: '高级版',
    userInfo: '2026-02-20 注册，已完成实名认证',
    subscriptionInfo: '高级版 1 年，剩余 348 天',
    discountInfo: '年费折扣 15%',
    commissionText: '本单可得佣金 20.7 元',
    commissionStatus: '可提现',
    withdrawalOffsetDays: -1,
    withdrawalHour: 18,
    withdrawalMinute: 20,
    withdrawalStatus: '审核中',
    withdrawalAmount: 120.5,
    joinedOffsetDays: -18,
    joinedHour: 9,
    joinedMinute: 0,
    agentLevel: '实习代理',
  },
  {
    id: 2,
    memberName: '阿川选货',
    versionName: '铂金版',
    userInfo: '2026-01-08 注册，近 30 天成交 6 单',
    subscriptionInfo: '铂金版 1 年，剩余 306 天',
    discountInfo: '年费折扣 20%',
    commissionText: '累计佣金 86.4 元',
    commissionStatus: '已结算',
    withdrawalOffsetDays: -12,
    withdrawalHour: 10,
    withdrawalMinute: 12,
    withdrawalStatus: '已完成',
    withdrawalAmount: 86.4,
    joinedOffsetDays: -58,
    joinedHour: 12,
    joinedMinute: 0,
    agentLevel: '铜牌代理',
  },
  {
    id: 3,
    memberName: '数码补货站',
    versionName: '专业版',
    userInfo: '2026-03-01 注册，等待完善资料',
    subscriptionInfo: '专业版试用中',
    discountInfo: '待设置折扣',
    commissionText: '完成首单后可解锁佣金',
    commissionStatus: '待开通',
    withdrawalOffsetDays: null,
    withdrawalHour: null,
    withdrawalMinute: null,
    withdrawalStatus: '未申请',
    withdrawalAmount: 0,
    joinedOffsetDays: -8,
    joinedHour: 14,
    joinedMinute: 0,
    agentLevel: '实习代理',
  },
] as const;
